[package]
name = "c_struct_size"
version = "0.1.0"
authors = []

[lib]
name = "c_struct_size"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.19.0"
rustler_codegen = "0.19.0"
lazy_static = "1.0"
